# Generated by Django 3.2.6 on 2021-09-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rassperySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, verbose_name='توکن اتصال')),
                ('serial_rasperyPi', models.CharField(blank=True, max_length=16, null=True, verbose_name='سریال رزپری پای')),
            ],
            options={
                'verbose_name': 'سیستم ها(رزپری پای)',
                'verbose_name_plural': 'سیستم ها(رزپری پای)',
            },
        ),
    ]
