# Generated by Django 3.2.6 on 2021-09-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='rassperySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, verbose_name='توکن اتصال')),
                ('serial_rasperyPi', models.CharField(blank=True, max_length=16, null=True, verbose_name='سریال رزپری پای')),
                ('serial_reset_password', models.CharField(max_length=12)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profiles')),
            ],
            options={
                'verbose_name': 'سیستم ها(رزپری پای)',
                'verbose_name_plural': 'سیستم ها(رزپری پای)',
            },
        ),
    ]
