# Generated by Django 3.2.7 on 2021-09-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rassperysystem',
            name='serial_rasperyPi',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='سریال رزپری پای'),
        ),
        migrations.AlterField(
            model_name='rassperysystem',
            name='token',
            field=models.CharField(max_length=256, unique=True, verbose_name='توکن اتصال'),
        ),
    ]
