# Generated by Django 3.2.7 on 2021-10-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0002_auto_20210926_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='rassperysystem',
            name='online_status',
            field=models.IntegerField(choices=[(1, 'سیستم متصل است'), (2, 'سیستم آفلاین است')], default=2, verbose_name='وضعیت درخواست'),
        ),
    ]
