# Generated by Django 3.2.7 on 2021-10-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0003_rassperysystem_online_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rassperysystem',
            name='serial_reset_password',
        ),
    ]
