# Generated by Django 3.2.7 on 2021-10-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0004_remove_rassperysystem_serial_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='rassperysystem',
            name='address',
            field=models.TextField(default=1, verbose_name='آدرس محل نصب'),
            preserve_default=False,
        ),
    ]
