# Generated by Django 3.2.7 on 2021-11-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0005_rassperysystem_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='rassperysystem',
            name='hash_serial_rassperyPi',
            field=models.CharField(default='c04c4a49c663a208f25b785502678574dc862a0f6addac01c2b88ee953cc2907', max_length=64, verbose_name='hash سریال رزپری پای'),
        ),
        migrations.AlterField(
            model_name='rassperysystem',
            name='serial_rasperyPi',
            field=models.CharField(default=1, max_length=16, unique=True, verbose_name='سریال رزپری پای'),
            preserve_default=False,
        ),
    ]
