# Generated by Django 3.2.7 on 2021-11-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0006_auto_20211104_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rassperysystem',
            name='hash_serial_rassperyPi',
            field=models.CharField(blank=True, default='c04c4a49c663a208f25b785502678574dc862a0f6addac01c2b88ee953cc2907', max_length=64, null=True, verbose_name='hash سریال رزپری پای'),
        ),
    ]
