# Generated by Django 3.2.7 on 2021-11-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0007_alter_rassperysystem_hash_serial_rassperypi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rassperysystem',
            name='hash_serial_rassperyPi',
            field=models.CharField(default=1, max_length=64, verbose_name='hash سریال رزپری پای'),
            preserve_default=False,
        ),
    ]
