# Generated by Django 3.2.7 on 2021-11-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0010_alter_rassperysystem_hash_serial_rassperypi'),
    ]

    operations = [
        migrations.AddField(
            model_name='rassperysystem',
            name='title',
            field=models.CharField(default=1, max_length=80, verbose_name='عنوان رزری پای'),
            preserve_default=False,
        ),
    ]
