# Generated by Django 3.2.7 on 2021-11-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0011_rassperysystem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='rassperysystem',
            name='type_rassperyPi',
            field=models.IntegerField(choices=[(0, 'رزپری پای4'), (1, 'رزپری پای صفر')], default=1, verbose_name='نوع رزپری پای'),
            preserve_default=False,
        ),
    ]
