# Generated by Django 3.2.7 on 2021-10-03 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='تلفن همراه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'نمایه کاربری',
                'verbose_name_plural': 'نمایه کاربری',
            },
        ),
        migrations.CreateModel(
            name='AuthSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSend', models.DateTimeField(auto_now_add=True, verbose_name='تایم ارسال SMS')),
                ('codeSended', models.IntegerField(verbose_name='کد ارسال شده')),
                ('token', models.CharField(max_length=300, verbose_name='توکن برای احراز')),
                ('type_SMS', models.IntegerField(choices=[(1, 'ریست کردن پسوورد'), (2, 'احراز موبایل')], verbose_name='نوع پیام')),
                ('state_SMS', models.IntegerField(choices=[(1, 'پیام ارسال شده'), (2, 'منقضی شده'), (3, 'از پیام برای احراز استفاده شده'), (4, 'از پیام برای تغییر رمز استفاده شد')], default=1, verbose_name='وضعیت پیام')),
                ('profileUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profiles', verbose_name='پروفایل فرد مورد احراز')),
            ],
            options={
                'verbose_name': 'SMSهای احراز هویت',
                'verbose_name_plural': 'SMSهای احراز هویت',
            },
        ),
    ]
