# Generated by Django 3.2.7 on 2021-10-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='serial_reset_password',
            field=models.CharField(default=123456789123, max_length=12),
            preserve_default=False,
        ),
    ]
