# Generated by Django 3.2.7 on 2021-12-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profiles_serial_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsms',
            name='state_SMS',
            field=models.IntegerField(choices=[(1, 'پیام ارسال شده'), (2, 'منقضی شده'), (3, 'استفاده شده')], default=1, verbose_name='وضعیت پیام'),
        ),
    ]
