# Generated by Django 3.2.7 on 2021-10-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0004_remove_rassperysystem_serial_reset_password'),
        ('doorSecurity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensetouse',
            options={'verbose_name': 'مدیریت lincense بازکردن درب', 'verbose_name_plural': 'مدیریت lincense بازکردن درب'},
        ),
        migrations.RemoveField(
            model_name='licensetouse',
            name='rassperypiInfo',
        ),
        migrations.CreateModel(
            name='InformationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_opendoor', models.IntegerField(choices=[(1, 'باز شود.'), (2, 'باز نشود.')], default=1, verbose_name='وضعیت باز شدن درب')),
                ('address', models.TextField(verbose_name='آدرس محل نصب')),
                ('lincense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doorSecurity.licensetouse')),
                ('rassperypiInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rassperypiInfo.rassperysystem')),
            ],
            options={
                'verbose_name': 'مدیریت اطلاعات سرویس',
                'verbose_name_plural': 'مدیریت اطلاعات سرویس',
            },
        ),
    ]
