# Generated by Django 3.2.7 on 2021-09-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0001_initial'),
        ('doorSecurity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoryOpenDoor',
            new_name='HistoryDoorSecurity',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='change_status',
            new_name='change_status_date',
        ),
    ]
