# Generated by Django 3.2.7 on 2021-10-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doorSecurity', '0002_auto_20211012_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationservice',
            name='address',
        ),
    ]
