# Generated by Django 3.2.7 on 2021-09-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorSecurity', '0002_auto_20210926_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydoorsecurity',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doorSecurity.members'),
        ),
    ]
