# Generated by Django 3.2.7 on 2021-11-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorSecurity', '0003_remove_informationservice_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='picture',
            field=models.ImageField(default=1, upload_to='person_image', verbose_name='عکس شخص'),
            preserve_default=False,
        ),
    ]
