# Generated by Django 3.2.7 on 2021-09-26 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0001_initial'),
        ('doorSecurity', '0004_alter_historydoorsecurity_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydoorsecurity',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doorSecurity.members'),
        ),
        migrations.AlterField(
            model_name='historydoorsecurity',
            name='rassperypiInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rassperypiInfo.rassperysystem'),
        ),
    ]
