# Generated by Django 3.2.7 on 2021-09-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorSecurity', '0005_auto_20210926_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
