# Generated by Django 3.2.7 on 2021-11-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rassperypiInfo', '0011_rassperysystem_title'),
        ('doorSecurity', '0005_auto_20211114_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetouse',
            name='rassperypiInfo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rassperypiInfo.rassperysystem'),
            preserve_default=False,
        ),
    ]
