# Generated by Django 3.2.7 on 2021-11-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorSecurity', '0006_licensetouse_rassperypiinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='picture',
            field=models.TextField(default=1, verbose_name='عکس شخص'),
            preserve_default=False,
        ),
    ]
