# Generated by Django 3.2.7 on 2021-09-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorSecurity', '0006_alter_members_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydoorsecurity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='licensetouse',
            name='start_lincense',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='change_status_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
