# Generated by Django 3.2.7 on 2022-04-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorSecurity', '0007_history_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='allow_status',
            field=models.IntegerField(choices=[(1, 'فرد اجازه ورود دارد'), (0, 'فرد اجازه ورود ندارد')], default=1, verbose_name='وضعیت دسترسی فرد'),
        ),
    ]
